# Generated by Django 5.1.7 on 2025-04-11 09:52

import first.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(upload_to=first.models.pdf_upload_path),
        ),
    ]
